name: Publish on PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Publish tagged release on PyPI

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'

      - name: Ensure package version and tag name are equal
        id: check-package
        run: |
          PKG_VER="$(grep -oP '^version = "\K[^"]+' pyproject.toml)"
          TAG_VER="${GITHUB_REF##*/}"
          echo "Package version is $PKG_VER" >&2
          echo "Tag version is $TAG_VER" >&2
          if [ "$PKG_VER" != "$TAG_VER" ]; then
            echo "Package version and tag name mismatch." >&2
            exit 1
          fi

      - name: Install dependencies
        id: install
        run: uv sync --extra dev

      - name: Run pytest
        id: test
        run: uv run pytest tests

      - name: Build a binary wheel and a source tarball
        id: build
        run: uv build

      - name: Publish distribution package to PyPI (test)
        id: publish-test
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      - name: Publish distribution package to PyPI (production)
        id: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
