name: Run test suite and measure coverage

on: push

jobs:
  tests:
    name: Run test suite (Python ${{ matrix.python-version }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.13', '3.14']

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run tests
        id: pytest
        run: |
          uv run pytest \
            --cov=jsonsubschema \
            --cov-report=xml \
            tests

      - name: Upload coverage to coveralls
        id: coveralls
        if: matrix.python-version == '3.13'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade coveralls
          coveralls --service=github
