name: Run test suite

on: push

jobs:
  tests:
    name: Run tests (Python ${{ matrix.python-version }}${{ matrix.coverage && ', with coverage' || '' }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - python-version: '3.13'
            coverage: true
          - python-version: '3.14'
            coverage: false

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run tests with coverage
        if: ${{ matrix.coverage == true }}
        id: pytest
        run: |
          uv run pytest \
            --cov=jsonsubschema \
            --cov-report=xml \
            tests

      - name: Run tests without coverage
        if: ${{ matrix.coverage != true }}
        id: pytest_no_cov
        run: uv run pytest tests

      - name: Upload coverage to coveralls
        id: coveralls
        if: ${{ matrix.coverage == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade coveralls
          coveralls --service=github
